### ISSUE TITLE
Doppelklick auf CR öffnet Karte nicht mehr direkt

### ISSUE THREAD

**Issue by Xolgrim** [ennorehling/csmapfx#6]
Unter Windos führt ein Doppelklick auf einen CR nur noch zum start des leeren CSMap ohne dass die angecklickte Karte direkt geladen wird wie es früher war.

**Comment by ennorehling** [comment]
Die Dateien wurden geldaen, aber die Anzeige nicht aktualisiert. Wird auch in Version 0.9.8 gefixt sein.
