### ISSUE TITLE
anonyme Einheiten werden falsch dargestellt

### ISSUE THREAD

**Issue by Xolgrim** [ennorehling/csmapfx#7]
Anonyme Einheiten wie z.B. "Wenming (4xec), anonym, 1 Katze, hat:" in cr 1246 von Partei (777) (Report liegt dir vor) werden in CSMap als "Unbekannt (3w5e11264sgsf)" angezeigt.
Eine Anzeige als Unbekannt komplett ohne Nummer wäre vermutlich das sinnigst, da das im NR auch so geregelt wird.

**Comment by ennorehling** [comment]
Da wurde versucht, die Zahl -1 als base36 darzustellen. Ich fixe das mit Version 0.9.8
