### ISSUE TITLE
Der Dateiname des CR wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by Xolgrim** [ennorehling/csmapfx#8]
Der Dateiname des zuerst geöffneten CR wird nicht mehr angezeigt.
Früher stand diese Information oben Links, in der aktuellen Version ist dort nur noch eine leere Eckige Klammer zu sehen: []
V0.9.8

**Comment by ennorehling** [comment]
![image](https://user-images.githubusercontent.com/629521/146410607-e1a33930-79b5-4ee1-a01f-578242335d91.png)

Kann ich nicht reproduzieren.

**Comment by ennorehling** [comment]
Gefunden, Bug wird gefixt in Version 0.9.9
